# Generated by Django 5.2.6 on 2025-09-19 23:46

import django.db.models.deletion
import django.utils.timezone
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tech_logos/')),
                ('alt', models.CharField(blank=True, max_length=50, null=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TechCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=55)),
                ('large', models.ImageField(upload_to=project.models.get_url_image)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('live_demo_url', models.URLField(blank=True, help_text='Live demo URL', null=True)),
                ('alt', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date/time submitted')),
                ('visible', models.BooleanField(default=False)),
                ('technologies', models.ManyToManyField(blank=True, help_text='Technologies used in this project', null=True, to='project.tech')),
            ],
        ),
        migrations.AddField(
            model_name='tech',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='project.techcategory'),
        ),
    ]
