# Generated by Django 5.2.6 on 2025-09-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
        migrations.AddField(
            model_name='tech',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
    ]
