# Generated by Django 5.2.6 on 2025-09-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_order_tech_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='large',
            new_name='image',
        ),
    ]
