# Generated by Django 5.2.6 on 2025-09-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_large_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in this project', to='project.tech'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/tech_logos/'),
        ),
    ]
