# Generated by Django 5.2.6 on 2025-09-20 00:26

import imagekit.models.fields
import project.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_technologies_alter_tech_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=project.models.get_url_image),
        ),
        migrations.AlterField(
            model_name='tech',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(upload_to=project.models.get_url_tech_logo),
        ),
    ]
