# Generated by Django 5.2.6 on 2025-09-21 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_image_alter_tech_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcategory',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techcategory',
            name='light_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tech',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='project.techcategory'),
        ),
    ]
