# Generated by Django 5.2.6 on 2025-09-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_techcategory_color_techcategory_light_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techcategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='techcategory',
            name='light_color',
        ),
    ]
